export const actionTypes = {
  ADD_PARTICIANT: 'ADD_PARTICIANT',
  REMOVE_PARTICIANT: 'REMOVE_PARTICIANT',
  ADD_NEW_PARTICIANT: 'ADD_NEW_PARTICIANT',
  SHOW_WINNER: 'SHOW_WINNER',
  SET_IS_SHOW_TIMER: 'SET_IS_SHOW_TIMER',
  SET_IS_SHOW_NOTIFICATION: 'SET_IS_SHOW_NOTIFICATION',
  SET_MESSAGE: 'SET_MESSAGE',
  SEARCH_PARTICIANT: 'SEARCH_PARTICIANT',
};
